# -*- coding: utf-8 -*-
"""Simple Fraud Detection Demo

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/196HNU8yeizhq8LvLWQiDkNWr32Ltkjp9
"""

# Simple Fraud Detection Demo in Google Colab
# --------------------------------------------

import pandas as pd
from sklearn.model_selection import train_test_split
from sklearn.linear_model import LogisticRegression
from sklearn.metrics import classification_report

# 1. Create a simple numeric dataset
data = {
    "amount": [5, 20, 50, 200, 500, 950, 1000, 7, 15, 850, 999, 30, 60, 300, 750]
}
df = pd.DataFrame(data)

# Label rule: fraud if amount < 10 or > 900
df["fraud"] = df["amount"].apply(lambda x: 1 if x < 10 or x > 900 else 0)

print("Dataset:")
print(df)

# 2. Split dataset
X = df[["amount"]]
y = df["fraud"]
X_train, X_test, y_train, y_test = train_test_split(X, y, test_size=0.3, random_state=42)

# 3. Train simple model
model = LogisticRegression()
model.fit(X_train, y_train)

# 4. Evaluate
y_pred = model.predict(X_test)
print("\nClassification Report:")
print(classification_report(y_test, y_pred))

# 5. Test with new numbers
test_numbers = pd.DataFrame({"amount": [1200, 15, 450, 90, 1000]})
predictions = model.predict(test_numbers)
print("\nPredictions on new numbers:")
print(pd.DataFrame({"amount": test_numbers["amount"], "fraud_prediction": predictions}))

import matplotlib.pyplot as plt

plt.scatter(test_numbers["amount"], predictions, color="red")
plt.xlabel("Amount")
plt.ylabel("Fraud Prediction")
plt.title("Fraud Predictions vs. Amounts")
plt.yticks([0, 1], ["Not Fraud", "Fraud"])
plt.show()

import matplotlib.pyplot as plt

# Count predicted classes
counts = pd.Series(predictions).value_counts()

# Define labels
labels = ["Not Fraud", "Fraud"]

# Make sure order matches your model's output (0=Not Fraud, 1=Fraud)
plt.pie(counts, labels=labels, autopct='%1.1f%%', startangle=90, colors=["skyblue", "salmon"])
plt.title("Fraud Prediction Distribution")
plt.show()